# constants and settings
IMG_CNT = 26
IMG_SIZE = 15
PIXEL_CNT = 5

POPULATION_SIZE = 120
GENERATION_CNT = 1000

PARTICIPATION_CNT = 5
CROSSOVER_RATE = 50
MUTATION_RATE = 7

SURVIVOR_CNT = 10

ISLAND_CNT = 3
ISLAND_CYCLES = 3000
ISLAND_CROSSOVER_RATE = 3
ISLAND_CROSSOVER_CNT = 7
